name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        name: Set up JDK 17
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Clean Gradle Cache and Build
        run: |
          ./gradlew --stop
          rm -rf ~/.gradle/caches/
          rm -rf build/

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: '7.6.4'

      - name: Build with Gradle
        if: ${{github.event_name == 'push'}}
        run: ./gradlew build -x text

      - name: Test with Gradle
        run: ./gradlew test

      - name: Generate JaCoCo Report
        run: ./gradlew jacocoTestReport

      - name: Upload JaCoCo coverage report
        uses: codecov/codecov-action@v3
        if: ${{ success() }}
        with:
          files: build/report/jacoco/test/jacocoTestReport.xml
          flags: unittests
          name: codecov-unit